export const ADJECTIVES = [
  'Able', 'Abundant', 'Active', 'Adaptable', 'Admirable',
  'Adventurous', 'Agile', 'Alert', 'Ambitious', 'Amiable',
  'Apt', 'Ardent', 'Assured', 'Attentive', 'Authentic',
  'Avid', 'Balanced', 'Bold', 'Brave', 'Bright',
  'Brisk', 'Brilliant', 'Buoyant', 'Calm', 'Capable',
  'Caring', 'Centered', 'Champion', 'Cheerful', 'Clear',
  'Clever', 'Committed', 'Confident', 'Connected', 'Consistent',
  'Courageous', 'Creative', 'Crisp', 'Daring', 'Dazzling',
  'Decisive', 'Dedicated', 'Dependable', 'Devoted', 'Diligent',
  'Dynamic', 'Eager', 'Earnest', 'Effective', 'Efficient',
  'Elite', 'Empowered', 'Energetic', 'Engaged', 'Enthusiastic',
  'Epic', 'Excellent', 'Expert', 'Fair', 'Fast',
  'Fearless', 'Fine', 'Firm', 'Flexible', 'Flourishing',
  'Focused', 'Forthright', 'Free', 'Fresh', 'Friendly',
  'Fulfilling', 'Gifted', 'Glad', 'Glowing', 'Golden',
  'Good', 'Graceful', 'Grand', 'Grateful', 'Great',
  'Hardy', 'Happy', 'Harmonious', 'Healthy', 'Helpful',
  'Honest', 'Hopeful', 'Humble', 'Imaginative', 'Impactful',
  'Industrious', 'Innovative', 'Insightful', 'Inspiring', 'Inventive',
  'Joyful', 'Keen', 'Kind', 'Laudable', 'Lively',
  'Logical', 'Loyal', 'Lucky', 'Luminous', 'Masterful',
  'Mighty', 'Mindful', 'Noble', 'Nimble', 'Nurturing',
  'Open', 'Optimistic', 'Orderly', 'Outstanding', 'Patient',
  'Peaceful', 'Persevering', 'Positive', 'Powerful', 'Proactive',
  'Productive', 'Proficient', 'Progressive', 'Proud', 'Pure',
  'Quick', 'Radiant', 'Ready', 'Reliable', 'Resilient',
  'Resolute', 'Resourceful', 'Respectful', 'Responsive', 'Rooted',
  'Sharp', 'Sincere', 'Skilled', 'Smart', 'Spirited',
  'Steady', 'Strategic', 'Strong', 'Sure', 'Swift',
  'Talented', 'Tenacious', 'Thoughtful', 'Thriving', 'Tireless',
  'Trusted', 'Truthful', 'Upbeat', 'Uplifting', 'Vibrant',
  'Victorious', 'Vigilant', 'Visionary', 'Vital', 'Warm',
  'Wholesome', 'Willing', 'Wise', 'Witty', 'Wonderful',
  'Worthy', 'Zealous', 'Zestful', 'Benevolent', 'Blissful',
  'Candid', 'Charitable', 'Composed', 'Considerate', 'Deft',
  'Earnest', 'Eloquent', 'Empathetic', 'Exemplary', 'Expressive',
  'Faithful', 'Fervent', 'Focused', 'Forthcoming', 'Gallant',
  'Genuine', 'Glorious', 'Gracious', 'Grounded', 'Heroic',
  'Idealistic', 'Illustrious', 'Impartial', 'Intuitive', 'Laudable',
  'Meticulous', 'Passionate', 'Polished', 'Prodigious', 'Steadfast',
];

export const VERBS = [
  'Accelerate', 'Achieve', 'Advance', 'Advocate', 'Amplify',
  'Animate', 'Aspire', 'Bloom', 'Boost', 'Brighten',
  'Build', 'Celebrate', 'Champion', 'Charge', 'Cheer',
  'Clarify', 'Commit', 'Connect', 'Contribute', 'Create',
  'Cultivate', 'Dare', 'Dedicate', 'Deliver', 'Develop',
  'Discover', 'Drive', 'Elevate', 'Embolden', 'Embrace',
  'Empower', 'Enable', 'Encourage', 'Energize', 'Engage',
  'Enrich', 'Envision', 'Excel', 'Excite', 'Expand',
  'Explore', 'Flourish', 'Focus', 'Forge', 'Foster',
  'Fuel', 'Grow', 'Guide', 'Heal', 'Ignite',
  'Illuminate', 'Imagine', 'Improve', 'Inspire', 'Integrate',
  'Invigorate', 'Launch', 'Lead', 'Learn', 'Leap',
  'Liberate', 'Lift', 'Motivate', 'Move', 'Nurture',
  'Overcome', 'Persist', 'Pioneer', 'Plan', 'Produce',
  'Progress', 'Propel', 'Protect', 'Pursue', 'Reach',
  'Realize', 'Renew', 'Rise', 'Run', 'Serve',
  'Shine', 'Share', 'Soar', 'Spark', 'Sprint',
  'Strengthen', 'Strive', 'Succeed', 'Support', 'Surge',
  'Sustain', 'Thrive', 'Transform', 'Unite', 'Unlock',
  'Uplift', 'Win', 'Wonder', 'Achieve', 'Act',
  'Adapt', 'Affirm', 'Aim', 'Appreciate', 'Arouse',
  'Attain', 'Attract', 'Awaken', 'Balance', 'Begin',
  'Bolster', 'Captivate', 'Catalyze', 'Collaborate', 'Commit',
  'Complete', 'Conquer', 'Craft', 'Delight', 'Dream',
  'Elevate', 'Engage', 'Enhance', 'Establish', 'Evolve',
  'Execute', 'Express', 'Facilitate', 'Flourish', 'Gather',
  'Generate', 'Give', 'Harmonize', 'Honour', 'Hone',
  'Hustle', 'Initiate', 'Innovate', 'Integrate', 'Invest',
  'Journey', 'Kindle', 'Launch', 'Leverage', 'Master',
  'Maximize', 'Navigate', 'Open', 'Optimize', 'Organise',
  'Overcome', 'Participate', 'Perform', 'Prioritize', 'Rally',
  'Refresh', 'Reinforce', 'Reinvent', 'Revive', 'Reward',
  'Shape', 'Simplify', 'Solve', 'Spark', 'Stand',
  'Streamline', 'Unleash', 'Validate', 'Venture', 'Volunteer',
  'Welcome', 'Yield', 'Accelerate', 'Appreciate', 'Believe',
  'Challenge', 'Cherish', 'Contribute', 'Cultivate', 'Deliver',
  'Embolden', 'Enable', 'Enrich', 'Ensure', 'Excel',
  'Flourish', 'Forge', 'Fuel', 'Grow', 'Heal',
  'Inspire', 'Move', 'Nurture', 'Pioneer', 'Progress',
  'Reach', 'Rise', 'Serve', 'Shine', 'Thrive',
];

// Positive, easy-to-remember words of 5–8 letters
const PASSWORD_WORDS = [
  'amber', 'bliss', 'bloom', 'brave', 'breeze',
  'bright', 'bronze', 'cheer', 'cherry', 'clarity',
  'cloud', 'coral', 'courage', 'crisp', 'daring',
  'delight', 'dream', 'energy', 'excel', 'faith',
  'flame', 'flair', 'flint', 'float', 'focus',
  'forest', 'fresh', 'gently', 'ginger', 'glade',
  'gleam', 'glint', 'glitter', 'glory', 'golden',
  'grace', 'grant', 'green', 'grove', 'guide',
  'haven', 'heart', 'herbal', 'hilltop', 'honey',
  'hope', 'ignite', 'island', 'jasper', 'joyful',
  'jumper', 'kindle', 'lancer', 'lively', 'loyal',
  'lucky', 'maple', 'marvel', 'meadow', 'merit',
  'mighty', 'mingle', 'novel', 'oasis', 'ocean',
  'onward', 'orange', 'outrun', 'peace', 'petal',
  'pillar', 'pine', 'plume', 'power', 'prism',
  'pure', 'quest', 'quilt', 'radiant', 'rally',
  'ranger', 'rapid', 'reach', 'ready', 'revel',
  'ridge', 'river', 'roam', 'rover', 'royal',
  'ruby', 'rustle', 'sage', 'serene', 'shimmer',
  'silver', 'slate', 'solar', 'sonar', 'spark',
  'spirit', 'spring', 'spry', 'star', 'steel',
  'stone', 'stream', 'stride', 'strong', 'summit',
  'sunny', 'swift', 'tender', 'thrive', 'timber',
  'topaz', 'torch', 'tower', 'trail', 'trust',
  'uplift', 'valor', 'vivid', 'voyage', 'warm',
  'waves', 'willow', 'wisdom', 'wonder', 'worthy',
];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateGroupName(): string {
  return pick(ADJECTIVES) + ' ' + pick(VERBS);
}

export function generateSharedKey(): string {
  const suffix = String(Math.floor(Math.random() * 900) + 100);
  return pick(PASSWORD_WORDS) + suffix;
}
